BACKGROUND = (3,3,3)
HEIGHT = 62 * 8 + 50
WHITE = (255, 255, 255)

UNIT_SIZE = 45

BALL_SIZE = 7
MAX_LEVEL_NUMBER = 11
OFFSET = 2
BLOCK_SIZE = UNIT_SIZE - OFFSET
BAR_WIDTH = 100
BAR_HEIGHT = 10
BAR_Y = HEIGHT - BAR_HEIGHT - 10
BALL_START_Y = BAR_Y - 100
BALL_START_SPEED_X = 1
BALL_START_SPEED_Y = 2
WIDTH = 4 + ((BLOCK_SIZE + OFFSET) * 10)  
BAR_X = (WIDTH / 2) - (BAR_WIDTH / 2)
BALL_START_X = BAR_X + (BAR_WIDTH / 2)